### ISSUE TITLE
additional message types

### ISSUE THREAD

**Issue by jsachs** [amida-tech/hl7#1]
Are there plans to support additional message types/segments any time soon? It looks like the code is written to be reasonably flexible as-is.

**Comment by Clement-TS** [comment]
up

**Comment by MatthewVita** [comment]
EDIT: change of plans :). Was talking about making use of an existing HL7 solution for Python or Java to get the entirety of messages. See my solution here: I put together the following HL7 node repo I was thinking about earlier: https://github.com/MatthewVita/node-hl7-complete

Thanks,

Matthew Vita

**Comment by jsachs** [comment]
Hey @MatthewVita,

I think your vision for this project is far beyond how our organization uses it. Right now, it's just a tiny library in one of our other projects, and introducing these changes would result in nontrivial work elsewhere.

However, please feel free to fork the project!

Best,
Jacob

**Comment by MatthewVita** [comment]
Hi @jsachs,

Good feedback. What I'm getting at is I'd like a complete HL7 module for node. It appears yours is the most popular but needs to support additional message types.

I will continue to look into this with Java, Python, and even C++ interfacing to leverage existing parsers like HL7 Hapi to get this desired coverage. If things work out how I'd like them to, the API wouldn't change much from the node side. If it is significantly different, I agree that making a separate fork/module altogether is appropriate (that is not to say that I wouldn't want feedback from you all, however!).

-Matthew

**Comment by MatthewVita** [comment]
@jsachs,

I put together the following HL7 node repo I was thinking about earlier: https://github.com/MatthewVita/node-hl7-complete

I still have a lot of clean up work to do with it but I'm super happy with the results so far (fully leveraging Hapi to do the heavy lifting of HL7 messages while just writing plain JavaScript).

Please let me know your thoughts!

Thanks,
-Matthew

**Comment by jsachs** [comment]
@MatthewVita,

I don't really have the time to fully review/test the repo, but it looks interesting. I'm curious as to the use case you are envisioning--is this just for better HL7 in Javascript?

-Jacob

**Comment by MatthewVita** [comment]
@jsachs,

Exactly. Nodejs library for JS->HL7 and HL7->JS (kind of like what HL7py is for Python).

Thanks,
Matthew

**Comment by MatthewVita** [comment]
@jsachs,

Hi there. Wanted to get in touch with you after following up on https://github.com/amida-tech/mllp/pull/6

I've asked some folks at work (healthcare industry... we have a coding community that collaborates on internal and open source projects) to help test and unit test my https://github.com/MatthewVita/node-hl7-complete library. I think it may be a good idea to eventually start talking with you about maybe merging that library with this one to achieve significant coverage of HL7 message types.

Some impacts to consider:
- Would be a breaking change for all consumers, but I would be happy to provide migration documentation to make things easier.
- The mllp library depends on this library, so that would have to be tweaked and tested with more messages (also would be happy to do that).

This is long term stuff. Would love to see Node become a more serious option in the healthcare systems space and I think your team has done great work to make this a reality!

Thanks,
Matthew

**Comment by jsachs** [comment]
Hey @MatthewVita,

We're definitely open to merging your node library with this one. As far as breaking changes are concerned, that's fine. We can just use a new major version--we didn't have planned dev for this library anyways. Same goes for MLLP.

As I mentioned before, our team doesn't currently have the bandwidth to drive this development. However, we're happy to test and provide feedback, especially if we get closer to merging codebases.

**Comment by MatthewVita** [comment]
@jsachs,

Sounds good. Still have a _lot_ of unit testing to do on my end, but this sounds like a great plan!

Thanks,
Matthew

**Comment by MatthewVita** [comment]
@jsachs,

Finally found some time to get testing in for my library. I marked it as version 1 and all that's really left is to test it on Windows: https://github.com/MatthewVita/node-hl7-complete

Let me know what you think and we can discuss the possibility of merging.

Thanks,
Matthew

**Comment by jsachs** [comment]
@MatthewVita,

I tried to run your tests on my local machine. Even though you mention Java 8 in your specs, the functional tests threw an error that I needed the legacy Java 6 runtime.

**Comment by MatthewVita** [comment]
Hi @jsachs,

Check out the following bit of the README from the Java NPM module here: https://github.com/joeferner/node-java#installation-osx - should fix your issue.

I'm thinking that it may make sense to update my repo's README to point out that ones system must be setup to work with the Java NPM module. A bit leaky, but this is the cost to get the benefits of HAPI. Thoughts?

Thanks,
Matthew

**Comment by jsachs** [comment]
@MatthewVita, I was able to run the tests and this looks good. Still discussing with @mhiner about mergeability.

For our own edification, what do you see as the greatest benefit of merging this with our repo? Right now, one of the advantages of our hl7 library is that it is very light, and the Java dependency would make it very heavy. Would it be bad to leave them as two separate libraries, and perhaps add README references?

**Comment by MatthewVita** [comment]
Hi @jsachs,

Glad you got the tests to run.

Greatest benefit of my repo is the HL7 coverage. Your HL7 library does support common segments, but folks looking for more coverage would benefit from my library. I agree that my library has a lot more overhead (I put a note in my README about that).

I think the following would work in your README:

## Notes
- For those that need to support additional message types, check out https://github.com/MatthewVita/node-hl7-complete

**Comment by jsachs** [comment]
I've updated the README to reference your library, with some rudimentary drop-in instructions as well. Thank you for all the hard work!

**Comment by MatthewVita** [comment]
Nice working with you!
